name: gha for matrix
on: push
jobs:
  deploy:
    continue-on-error: true
    strategy:
      matrix:
        node-versions: [12,14,16]
        os: [ubuntu-latest,windows-latest]
        include:
          - node-versions: 18
            os: ubuntu-latest
        exclude:
          - node-versions: 12
            # os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Node js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Building app
        run: npm run build
      - name: Deploying the app
        uses: ./.github/workflows/reusable-wf.yml