name: gha for matrix
on: push
jobs:
  deploy:
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        node-versions: [18]
        os: [ubuntu-latest]
        # include:
        #   - node-versions: 18
        #     os: ubuntu-latest
        # exclude:
        #   - node-versions: 12
        #     os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Node js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Building app
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-artifact
          path: dist
  reusable-job:
    uses: ./.github/workflows/reusable-wf.yml
    needs: [ deploy ]
    with:
      artifact: npm-artifact
    # secrets:
    #   imp-secret: ${{ secrets.imp-secret }}
  
  print-reusable-result:
    needs: [reusable-job]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.reusable-job.outputs.result }}"