name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact:
        type: string
        description: Name of the artifact built
        required: false
        default: npm
    # secrets:
    #   imp-secret:
    #     required: false
    outputs:
      result:
        description: "Printing job status"
        value: ${{ jobs.deploy.outputs.job-status }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ steps.set-output.outputs.status }}
      
    steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact }}
      - name: Deploying the package
        run: |
          echo "Deployment started"
          sleep 10
          echo "Deployment completed"
      - name: Output values
        id: set-output
        run: echo "status=success" > $GITHUB_OUTPUT